# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ggmfit <- function(S, n, K, nvar, glen, gg, iter, eps) {
    .Call('_gRim_cpp_ggmfit', PACKAGE = 'gRim', S, n, K, nvar, glen, gg, iter, eps)
}

ghk2pmsParms_ <- function(parms) {
    .Call('_gRim_ghk2pmsParms_', PACKAGE = 'gRim', parms)
}

pms2ghkParms_ <- function(parms) {
    .Call('_gRim_pms2ghkParms_', PACKAGE = 'gRim', parms)
}

updateA <- function(A, E, row, col) {
    .Call('_gRim_updateA', PACKAGE = 'gRim', A, E, row, col)
}

update_ghkParms_ <- function(Cparms, dgen_idx, cgen_idx, ghk_obs, pms_obs, ghk_fit, pms_fit, scale, details = 0) {
    .Call('_gRim_update_ghkParms_', PACKAGE = 'gRim', Cparms, dgen_idx, cgen_idx, ghk_obs, pms_obs, ghk_fit, pms_fit, scale, details)
}

normalize_ghkParms_ <- function(parms) {
    .Call('_gRim_normalize_ghkParms_', PACKAGE = 'gRim', parms)
}

